version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: backend
    restart: always
    ports:
      - "80:80"
    networks:
      - deploy-guide-dev
    depends_on:
      - postgres
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: soskot
    networks:
      - deploy-guide-dev
    volumes:
      - postgres-data:/var/lib/postgres/data
    healthcheck:
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 20s
networks:
  deploy-guide-dev:
    driver: bridge
volumes:
  postgres-data:

